# Generated by Django 5.2 on 2025-07-09 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_produto_imagem_produto_imagem_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('excluido', models.BooleanField(default=False)),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='produto',
            name='em_carrosel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='produto',
            name='em_destaque',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='produto',
            name='em_promocao',
            field=models.BooleanField(default=False),
        ),
    ]
